export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'; 
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';